nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: /Users/cbjohnson/Projects/Personal/super_happy_interview_time/ts/.yarn/releases/yarn-berry.js
