---
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-sorbet

# rubocop
Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# sorbet
Sorbet/EnforceSignatures:
  Enabled: false

Sorbet/FalseSigil:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: false

Sorbet/StrongSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: false
