---
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-sorbet
  - standard

inherit_mode:
  merge:
    - Exclude

inherit_gem:
  standard: config/base.yml

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Sorbet/EnforceSignatures:
  Enabled: false

Sorbet/FalseSigil:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: false

Sorbet/StrongSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: false

Style/Documentation:
  Enabled: false
