---
inherit_gem:
  standard: config/base.yml

Style/BlockDelimiters:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
