---
Layout/ArgumentAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
