---
require:
  - standard
  - rubocop-minitest

inherit_mode:
  merge:
    - Exclude

inherit_from:
  - .rubocop.standard.yml

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - coverage/*
    - vendor/*

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false
