---
inherit_gem:
  standard: config/ruby-3.0.yml

Style/BlockDelimiters:
  EnforcedStyle: always_braces
  IgnoredMethods: []

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
