---
inherit_from:
  - .rubocop.sorbet.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-sorbet

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false
