# frozen_string_literal: true

ruby("~> 3.1")
source("https://rubygems.org")

gem("algorithms", "~> 1.0")
gem("awesome_print", "~> 1.9")
gem("debug", "~> 1.4")
gem("parser", "~> 3.0", require: false)
gem("rubocop", "~> 1.26", require: false)
gem("rubocop-minitest", "~> 0.18", require: false)
gem("standard", "~> 1.8", require: false)

group(:test) {
  gem("minitest", "~> 5.15")
  gem("minitest-reporters", "~> 1.5")
  gem("simplecov", "~> 0.18")
}
