# typed: false
# frozen_string_literal: true

ruby("3.0.3")
source("https://rubygems.org")

gem("debug", "~> 1.3")
gem("minitest", "~> 5.14")
gem("minitest-reporters", "~> 1.4")
gem("parser", "~> 3.0")
gem("rubocop", "~> 1.23")
gem("rubocop-minitest", "~> 0.17")
gem("rubocop-sorbet", "~> 0.6")
gem("simplecov", "~> 0.18")
gem("sorbet", "~> 0.5")
gem("sorbet-runtime", "~> 0.5")
gem("standard", "~> 1.5")
