default:
    @just --list

# Print this help message
help: default

# Build the project
build *OPTS:
    @bin/bundle install {{ OPTS }}

# Remove build artifacts
clean:
    @rm -rf coverage
    @rm -rf vendor/bundle

# Run the formatter
fmt *OPTS:
    @bin/rubocop --auto-correct {{ OPTS }}

# Run the linter
lint *OPTS:
    @bin/rubocop {{ OPTS }}

# Run the refactoring tool
refactor *OPTS:
    @bin/bundle exec ruby lib/refactor/main.rb code {{ OPTS }}
    @bin/bundle exec ruby lib/refactor/main.rb file {{ OPTS }}

# Run the tests
test *OPTS:
    @bin/minitest {{ OPTS }}

# Run the type checker
typecheck *OPTS:
    @bin/srb typecheck {{ OPTS }}
