# typed: false
# frozen_string_literal: true

require("rake/testtask")

task(default: :test)

Rake::TestTask.new { |task|
  task.libs = %w[lib test]
  task.test_files = FileList.new("test/**/test_*.rb")
}
