# frozen_string_literal: true

require 'rubygems'
require 'bundler/setup'

require 'irb'
require 'rake/testtask'

task default: :test

Rake::TestTask.new do |task|
  task.libs = %w[lib test]
  task.test_files = FileList.new('test/**/test_*.rb')
end

task :console do
  $LOAD_PATH.unshift(File.expand_path('.'))
  ARGV.clear
  IRB.start
end
