---
on: push

jobs:
  rb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: actions/cache@v1
        with:
          path: rb/vendor/bundle
          key: rb-${{ hashFiles('rb/Gemfile.lock') }}
          restore-keys: |
            rb-${{ hashFiles('rb/Gemfile.lock') }}
            rb-
      - run: gem install bundler --no-document
      - run: make rb deps OPTS='--frozen --deployment'
      - run: make rb check
      - run: make rb lint
      - run: make rb test

  rs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - run: make rs build
      - run: make rs check
      - run: make rs lint
      - run: make rs test
