---
on: push

jobs:
  rb:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rb/
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: rb/
      - run: just typecheck
      - run: just lint
      - run: just test

  rs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rs/
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
      - run: just build
      - run: just typecheck
      - run: just fmt -- --check
      - run: just lint
      - run: just test
