---
on: push

jobs:
  rb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install bundler --no-document
      - run: make rb deps OPTS='--frozen --deployment'
      - run: make rb check
      - run: make rb lint
      - run: make rb test

  rs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - run: make rs build
      - run: make rs check
      - run: make rs lint
      - run: make rs test

  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13'
      - uses: actions/cache@v1
        with:
          path: ts/.yarn/cache
          key: ts-${{ hashFiles('ts/yarn.lock') }}
          restore-keys: |
            ts-${{ hashFiles('ts/yarn.lock') }}
            ts-
      - run: make ts deps OPTS='--immutable --check-cache'
      - run: make ts build
      - run: make ts check
      - run: make ts lint
      - run: make ts test
